import argparse
def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument('--exp', type=str,  default='xxxx', help='model_name')
    parser.add_argument('--max_epoch', type=int,  default=100, help='maximum epoch number to train')
    parser.add_argument('--client_num', type=int, default=9, help='client number')
    parser.add_argument('--batch_size', type=int, default=10, help='batch_size per gpu')
    parser.add_argument('--image_size', type=int, default=1024, help='image_size')
    parser.add_argument('--clip_value', type=float,  default=100, help='maximum epoch number to train')
    parser.add_argument('--meta_step_size', type=float,  default=1e-3, help='maximum epoch number to train')
    parser.add_argument('--base_lr', type=float,  default=0.0001, help='maximum epoch number to train')
    parser.add_argument('--deterministic', type=int,  default=1, help='whether use deterministic training')
    parser.add_argument('--seed', type=int,  default=1337, help='random seed')
    parser.add_argument('--gpu', type=str,  default='0', help='GPU to use')
    parser.add_argument('--display_freq', type=int, default=20, help='batch_size per gpu')
    parser.add_argument('--unseen_site', type=int, default=8, help='batch_size per gpu')
    parser.add_argument('--pretrain', type=str, default=None, help='pretrain model')
    parser.add_argument('--sam_ckpt', type=str, default=None, help='pretrain Sam model')
    parser.add_argument('--sam_type', default='vit_b' , help='sam type')
    parser.add_argument('--thd', type=bool, default=False , help='3d or not')
    parser.add_argument('--roi_size', type=int, default=96 , help='resolution of roi')
    parser.add_argument('--num_classes', type=int, default=1 , help='number of classes')
    parser.add_argument('--start_epoch', type=int, default=0 , help='start epoch for training')
    parser.add_argument('--data', type=str,  default='FeTS2022', help='dataset')
    parser.add_argument('--weights', type=str, default = 0, help='the weights file you want to test')
    parser.add_argument('--gpu_device', type=int, default=0, help='use which gpu')
    args = parser.parse_args()
    return args